name: Generate Activity Graph

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/activity-graph.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        # v1, pinned to commit
        uses: maurodesouza/github-readme-activity-graph-action@6411849745757299611a795fef822a31ca8d1d02
        with:
          username: timoncool
          options: theme=github-compact&hide_border=true&bg_color=0d1117&color=58a6ff&line=58a6ff&point=c9d1d9&area=true&area_color=58a6ff
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          message: "Update activity graph"
